### ISSUE TITLE
constants.clj case unmatched clause

### ISSUE THREAD

**Issue by birdspider** [uncomplicate/clojurecl#10]
https://github.com/uncomplicate/clojurecl/blob/master/src/clojure/uncomplicate/clojurecl/constants.clj#l181

```
user=> (info (first (devices (first (platforms)))))
IllegalArgumentException No matching clause: 16466  
   uncomplicate.clojurecl.constants/dec-device-partition-property (constants.clj:181)

;; (Integer/toHexString 16466)
;; "4052"
```

EDIT:
(it seems only when `#ifdef CL_VERSION_1_1`)
defined in `intel-opencl-sdk:/opt/intel/opencl-sdk/include/CL/cl_ext.h` as such:
```
#define CL_DEVICE_PARTITION_BY_NAMES_EXT            0x4052
#define CL_DEVICE_PARTITION_BY_NAMES_INTEL          0x4052
```

**Comment by blueberry** [comment]
Found the cause: it seems that Intel is not following the standard properly. The good news is that I know how to solve this anyway, so the bugfix will follow quickly.

**Comment by blueberry** [comment]
Does it work properly now (I didn't see your EDIT, so I found another, Intel-independent solution)?

**Comment by birdspider** [comment]
yes I does work now, I get a `uncomplicate.clojurecl.info.DeviceInfo` Instance with stuff in it

**Comment by blueberry** [comment]
Great! I hope you'll enjoy GPU programming in Clojure then!

**Comment by birdspider** [comment]
A few (lein) tests fail and I get a sigsev on the jvm, but I guess thats something for another time :)

**Comment by blueberry** [comment]
Now, to run clojurecl's tests and build it from the source, you'd have to use midje, **and have an OpenCL 2.0 platform**. Please use the release from leiningen.

Of course, if some of your tests fail, please create an issue and we could try to solve that.
