### ISSUE TITLE
Still problems with ClojureCL and Mac OS

### ISSUE THREAD

**Issue by amherag** [uncomplicate/clojurecl#11]
Well, as any mac at the moment I got OpenCL 1.2. I'm using ClojureCL 0.6.2, and also tested with 0.6.0. I just try to run

`(map info (platforms))`

And I get 

({:profile "FULL_PROFILE",
  :version "OpenCL 1.2 (Feb  7 2016 15:43:50)",
  :name "Apple",
  :vendor "Apple",
  :extensions
  #{"cl_APPLE_SetMemObjectDestructor" "cl_APPLE_query_kernel_names" "cl_APPLE_gl_sharing"
    "cl_APPLE_clut" "cl_khr_gl_event" "cl_APPLE_ContextLoggingFunctions"},
  :icd-suffix-khr #error {
 :cause "OpenCL error: CL_INVALID_VALUE."
 :data {:name "CL_INVALID_VALUE", :code -30, :type :opencl-error, :details "(clojure.core/aget res__21898__auto__ 0)"}
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "OpenCL error: CL_INVALID_VALUE."
   :data {:name "CL_INVALID_VALUE", :code -30, :type :opencl-error, :details "(clojure.core/aget res__21898__auto__ 0)"}
   :at [clojure.core$ex_info invokeStatic "core.clj" 4617]}]
 :trace
 [[clojure.core$ex_info invokeStatic "core.clj" 4617]
  [clojure.core$ex_info invoke "core.clj" 4617]
  [uncomplicate.clojurecl.utils$error invokeStatic "utils.clj" 97]
  [uncomplicate.clojurecl.utils$error invokePrim "utils.clj" -1]
  [uncomplicate.clojurecl.info$icd_suffix_khr invokeStatic "info.clj" 77]
  [uncomplicate.clojurecl.info$icd_suffix_khr invoke "info.clj" 258]
  [uncomplicate.clojurecl.info$eval22182$fn__22183$fn__22195 invoke "info.clj" 279]
  [uncomplicate.clojurecl.info$eval22182$fn__22183 invoke "info.clj" 279]
  [uncomplicate.clojurecl.info$eval21959$fn__21960$G__21950__21969 invoke "info.clj" 232]
  [clojure.core$map$fn__4785 invoke "core.clj" 2644]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.LazySeq first "LazySeq.java" 71]
  [clojure.lang.RT first "RT.java" 667]
  [clojure.core$first__4339 invokeStatic "core.clj" 55]
  [clojure.pprint$pprint_reader_macro invokeStatic "dispatch.clj" 50]
  [clojure.pprint$pprint_list invokeStatic "dispatch.clj" 77]
  [clojure.pprint$pprint_list invoke "dispatch.clj" 76]
  [clojure.lang.MultiFn invoke "MultiFn.java" 229]
  [clojure.pprint$write_out invokeStatic "pprint_base.clj" 194]
  [clojure.pprint$pprint$fn__8473 invoke "pprint_base.clj" 249]
  [clojure.pprint$pprint invokeStatic "pprint_base.clj" 248]
  [clojure.pprint$pprint invoke "pprint_base.clj" 241]
  [clojure.pprint$pprint invokeStatic "pprint_base.clj" 245]
  [clojure.pprint$pprint invoke "pprint_base.clj" 241]
  [clojure.lang.Var invoke "Var.java" 379]
  [cider.nrepl.middleware.pprint$wrap_pprint_fn$fn__40198$fn__40200 invoke "pprint.clj" 55]
  [cider.nrepl.middleware.pprint$pprint_reply$fn__40215 invoke "pprint.clj" 83]
  [cider.nrepl.middleware.pprint$pprint_reply invokeStatic "pprint.clj" 76]
  [cider.nrepl.middleware.pprint$pprint_reply invoke "pprint.clj" 74]
  [cider.nrepl.middleware.pprint$pprint_transport$reify__40220 send "pprint.clj" 93]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__38240$fn__38253 invoke "interruptible_eval.clj" 113]
  [clojure.main$repl$read_eval_print__7408 invoke "main.clj" 241]
  [clojure.main$repl$fn__7417 invoke "main.clj" 258]
  [clojure.main$repl invokeStatic "main.clj" 258]
  [clojure.main$repl doInvoke "main.clj" 174]
  [clojure.lang.RestFn invoke "RestFn.java" 1523]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__38240 invoke "interruptible_eval.clj" 87]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 646]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1881]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1881]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invokeStatic "interruptible_eval.clj" 85]
  [clojure.tools.nrepl.middleware.interruptible_eval$evaluate invoke "interruptible_eval.clj" 55]
  [clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__38285$fn__38288 invoke "interruptible_eval.clj" 222]
  [clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__38280 invoke "interruptible_eval.clj" 190]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
  [java.lang.Thread run "Thread.java" 745]]}})

**Comment by blueberry** [comment]
Your code works well. See #8. 

Info tries to get all information, even the OpenCL 2.0 stuff that your platform knows nothing about. For these keys, particular nfo methods throw an exception, but info catches them and displays them instead of the value.

So, everything works well, enjoy using clojurecl and neanderthal.
