### ISSUE TITLE
Memory allocation failure

### ISSUE THREAD

**Issue by pdiffley** [uncomplicate/clojurecl#14]
I am receiving the error OpenCL error: CL_MEM_OBJECT_ALLOCATION_FAILURE after running a kernel several times. It works fine at first but after several calls it fails. My thought is that there may be an issue with the memory from the previous calls not being released even though I am using with-release.

I have attached my kernel and host code as txt files. 
[frame-kernel-host.txt](https://github.com/uncomplicate/clojurecl/files/423794/frame-kernel-host.txt)
The device I am running on is an AMD RX 480 8GB.  After 30 calls to run-select-frame3d, I get the error:

#error{:cause "OpenCL error: CL_MEM_OBJECT_ALLOCATION_FAILURE.",
       :data {:name "CL_MEM_OBJECT_ALLOCATION_FAILURE",
              :code -4,
              :type :opencl-error,
              :details "(->CLBuffer ctx res (Pointer/to res) size)"},
       :via [{:type clojure.lang.ExceptionInfo,
              :message "OpenCL error: CL_MEM_OBJECT_ALLOCATION_FAILURE.",
              :data {:name "CL_MEM_OBJECT_ALLOCATION_FAILURE",
                     :code -4,
                     :type :opencl-error,
                     :details "(->CLBuffer ctx res (Pointer/to res) size)"}

Subsequent calls to run-select-frame3d throw the same error until I restart the computer.
[frame-kernel-host.txt](https://github.com/uncomplicate/clojurecl/files/423795/frame-kernel-host.txt)
[frame-kernel.txt](https://github.com/uncomplicate/clojurecl/files/423796/frame-kernel.txt)

**Comment by blueberry** [comment]
Are you using the latest version of ClojureCL and commons?

Can you please try to extract those buffers out of the vector so that you have buffer0, buffer1, etc. instead of [buffer1 buffer2 ...]? Maybe a bug slipped in with-release when a sequence should be released.

I use quite a lot of creating/releasing in my custom kernels, with thousands cycles in loops, and do not have such problems.

**Comment by pdiffley** [comment]
That fixed it! Thanks!

**Comment by blueberry** [comment]
Can you prepare a leiningen project that demonstrates the problem and share it on github, so I can try it on my machine and fix the original bug related to releasing sequences?

Btw, what OS and drivers are you using with RX 480? Are you satisfied with performance?

**Comment by pdiffley** [comment]
I shared the project with you. Running the main function should lead to the error. It may give an explicit error message or just hang. 

I am using Ubuntu 16.04 64bit with AMD's beta driver (http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx). I installed the driver with a fresh install of Ubuntu to avoid any problems with drivers conflicting with each other. After installing the driver and rebooting, things have worked without a hitch. The performance has certainly met my needs, but I have not done any stress testing or benchmarking.

**Comment by blueberry** [comment]
@pdiffley I believe I solved that problem in uncomplicate/commons version 0.2.2
Please add that dependency explicitly in project.clj (because the current release of ClojureCL still uses 0.2.1) and check whether now release also works with sequences of releasable objects.

**Comment by pdiffley** [comment]
Ok. I should be able to check this tonight.

Phillip Diffley
HMC Physics '16
pdiffley@hmc.edu

**Comment by pdiffley** [comment]
It appears that with-release now works with sequences of releasable objects.

Thanks!

Phillip Diffley
HMC Physics '16
pdiffley@hmc.edu

**Comment by blueberry** [comment]
you're welcome.
