### ISSUE TITLE
vertigo dependency

### ISSUE THREAD

**Issue by Ciebiada** [uncomplicate/clojurecl#15]
Hi,

```
Exception in thread "main" java.io.FileNotFoundException: Could not locate vertigo/bytes__init.class or vertigo/bytes.clj on classpath., compiling:(uncomplicate/clojurecl/info.clj:1:1)
```

Looks like the vertigo dependency is no longer available

**Comment by blueberry** [comment]
It is available, but I mistakenly moved the dependency from main to dev profile. I will fix that in the next release, but right away you can fix this in your project by explicitly depending on vertigo 0.1.4 in your leiningen (or boot) project.

**Comment by Ciebiada** [comment]
Ok. Thanks for a quick response!

**Comment by blueberry** [comment]
@Ciebiada FYI in the latest commit, and in upcoming release 0.9.0, vertigo is no longer used nor needed.
