### ISSUE TITLE
passing direct byte buffer/memory address location instead of java array

### ISSUE THREAD

**Issue by zcaudate** [uncomplicate/clojurecl#22]
In this guide: https://dragan.rocks/articles/18/Interactive-GPU-Programming-2-Hello-OpenCL, all the data are in arrays.

Is it possible to use direct byte buffers?

**Comment by blueberry** [comment]
Direct byte buffers are the preferred way. Arrays are used in simple guides to not overload the newbies.

**Comment by zcaudate** [comment]
ah that's [awesome](https://github.com/uncomplicate/clojurecl/blob/master/test/clojure/uncomplicate/clojurecl/examples/openclinaction/ch07.clj#L30). thanks.
