### ISSUE TITLE
No implementation of method: :size of protocol for DirectFloatBufferS

### ISSUE THREAD

**Issue by zcaudate** [uncomplicate/clojurecl#23]
I'm getting an error whilst using a `java.nio.DirectFloatBufferS` for 

```
1. Unhandled java.lang.IllegalArgumentException
   No implementation of method: :size of protocol:
   #'uncomplicate.clojurecl.internal.protocols/Mem found for class:
   java.nio.DirectFloatBufferS

          core_deftype.clj:  583  clojure.core/-cache-protocol-fn
          core_deftype.clj:  575  clojure.core/-cache-protocol-fn
             protocols.clj:   18  uncomplicate.clojurecl.internal.protocols/eval32575/fn/G
                  core.clj: 1067  uncomplicate.clojurecl.core/enq-write!
                  core.clj: 1027  uncomplicate.clojurecl.core/enq-write!
                  core.clj: 1076  uncomplicate.clojurecl.core/enq-write!
                  core.clj: 1027  uncomplicate.clojurecl.core/enq-write!
                  base.clj:  203  hara.lib.opencl.base/opencl-write-input
```

adding this worked:

```
(extend-protocol uncomplicate.clojurecl.internal.protocols/Mem
  java.nio.DirectFloatBufferS
  (size [buff] (.capacity buff))
  (ptr [this] (org.jocl.Pointer/toBuffer this)))
```

**Comment by zcaudate** [comment]
though the computation then errors

**Comment by zcaudate** [comment]
Okay, I figured it out. It has to do with the endianess of the bytebuffer, the default in java is BigEndian unless specified.

To get rid of the error, this [form](https://github.com/uncomplicate/clojurecl/blob/master/src/clojure/uncomplicate/clojurecl/internal/impl.clj#L432-L437) can be replaced with something like:

```
  (def +lookup+
    {Float/TYPE Float/BYTES
     Double/TYPE Double/BYTES
     ;... ..
     })
  
  (defn component-size [buffer]
    (get +lookup+
         (.getReturnType (.getMethod (type buffer) "get" (into-array Class [])))))
  
  (extend-protocol uncomplicate.clojurecl.internal.protocols/Mem
    java.nio.Buffer
    (size [buff] (* (component-size buff)
                    (.capacity buff)))
    (ptr [this]
      (org.jocl.Pointer/toBuffer this))) 
```

**Comment by blueberry** [comment]
ClojureCL supports and prefers byte buffers and working with bytes. OpenCL, in contrast to Java, is byte oriented, and I'm afraid that supporting countless Java buffer implementations directly will only increase the challenge to the programmers. The only reason I added similar support for Java arrays is convenience for providing short parameters and writing simple examples for beginners.

If you really want to work with `DirectFloatBufferS` you can provide your own implementation in your code (as you have done in the code you've posted). However, I would recommend using Neanderthal vectors/matrices in combination with ClojureCL if your goal is just to work with Floats/Doubles instead of bytes, while writing your own OpenCL kernels.

**Comment by zcaudate** [comment]
`DirectFloatBufferS` cannot be obtained directly but comes about from calling `.asFloatBuffer` on a `DirectByteBuffer`, so they are related.

There's not really too much change. I'll put in a PR to show what I mean.

**Comment by blueberry** [comment]
Is there a reason you /need/ `FloatBuffer` specifically, and `ByteBuffer` does not work for you?

**Comment by zcaudate** [comment]
It's more for completeness, so that buffers can be used in all cases. I think the functionality should be provided as then the implementation becomes leaky.

If there is a float array object, a ByteBuffer can't be used to wrap the object and so a FloatBuffer has to be used. If I'm working with buffers and clojurecl, I don't need to think about the underlying implementation, ie: "This is a float buffer, clojurecl doesn't accept float buffers so I have to call `.array` on it and pass in the backing array".

or "This is a direct float buffer. clojurecl doesn't accept float buffers so in order to call it, I have to save the direct byte buffer that was used to create this and pass that in instead of the current float buffer"

---------

It's not that dramatic because of `extend-protocol` but yeah I would just rather pass in the buffer and it works.

**Comment by blueberry** [comment]
> If there is a float array object, a ByteBuffer can't be used to wrap the object and so a FloatBuffer has to be used. 

If there is a float array object, use it directly with ClojureCL, there is no point of wrapping it with buffers, nor does it help with anything regarding speed or functionality.

> If I'm working with buffers and clojurecl, I don't need to think about the underlying implementation, ie: 
> "This is a float buffer, clojurecl doesn't accept float buffers so I have to call `.array` on it and pass in the 
> backing array".

If you are using ClojureCL, I gues you're using it for speed. In that case, you better think about the underlying implementation - it's the most common thing that you can shoot yourself in the foot.

> or "This is a direct float buffer. clojurecl doesn't accept float buffers so in order to call it, I have to save the direct byte buffer that was used to create this and pass that in instead of the current float buffer"

Not at all. There is no way to create `DirectFloatBufferS`, other than from an already existing `DirectByteBuffer`. In that case, why not giving the original direct byte buffer to the ClojureCL? Why passing through the additional steps?

The message ClojureCL is sending you is not "convert, convert, convert", but "rethink what data structure you're sending me. I need raw bytes to ensure best performance and flexibility."

> It's not that dramatic because of `extend-protocol` but yeah I would just rather pass in the buffer and it works.

It would work, but how fast would it be?

**Comment by blueberry** [comment]
Don't get me wrong. I think that it'd be cool to support various bytebuffers for the sake of completeness. It would also be convenient in some situations. However, it should be thoroughly tested, to avoid giving an unintentional rope to the users to hang themselves with unintentionally.

And I am not how useful that would be in practice, since if you want to work with floats and doubles, I recommend combining ClojureCL with Neanderthal's vectors and matrices anyway, instead of working on the level of buffers...

**Comment by zcaudate** [comment]
FWIW, I'm wrapping clojurecl to create an fn-like instance which sets up all the buffer writing and reading. Something like this:

```
(def -mult-int-code-
    "__kernel void mult(__global uint * input,
                        uint n){
      int gid = get_global_id(0);
      input[gid] = n * input[gid];
    }")

(definvoke -mult-int-
  [:opencl {:name "mult"
            :code  -mult-int-code-
            :worksize (fn [{:strs [src]}]
                        [[(opencl-count src)]])
            :arglist [{:name "src"  :type :int-array  :input true  :output true}
                      {:name "n"    :type :int}]}])

(vec (buffer/buffer-read (-mult-int- (buffer/int-buffer [1 2 3 4 5]) 10)))
=> [10 20 30 40 50]

(vec (-mult-int- (int-array [1 2 3 4 5]) 10))
=> [10 20 30 40 50]
```

**Comment by blueberry** [comment]
Sure. Unfortunately, it does align completely with my views on how these things work, so I am reluctant to change my decision for now. 

It seems to me it is best that for now you use your own fork, or (which I think is better) an add-on library to ClojureCL with these extensions, gather more experience and test it more, so I can follow how it goes and maybe implement this in a future version of ClojureCL.

I'll close this for now, but feel free to re-open it in future.

**Comment by zcaudate** [comment]
@blueberry: no worries. like I said before, there's `extend-type`.
