### ISSUE TITLE
No namespace: uncomplicate.clojurecl.constants when requiring lib.

### ISSUE THREAD

**Issue by dkushner** [uncomplicate/clojurecl#6]
Forgive me, I'm very new to Clojure generally so I may just be making a newbie mistake but I've tried following the examples as closely as possible and have declared the following namespace specification:

```
(ns nbody.simulation
  (:require [uncomplicate.clojurecl.core :refer :all]))
```

And receive the following error:

```
CompilerException java.lang.Exception: No namespace: uncomplicate.clojurecl.constants, compiling:(uncomplicate/clojurecl/core.clj:1:1)
```

**Comment by blueberry** [comment]
I'd need to see the project.clj file where you set up the dependencies to be able to help you.

**Comment by dkushner** [comment]
@blueberry, of course, sorry about that.

```
(defproject nbody "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [uncomplicate/clojurecl "0.2.0"]
                 [org.clojure/tools.cli "0.3.3"]
                 [incanter "1.9.0"]]
  :main ^:skip-aot nbody.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

I'd like to say as well that, even for a relative newcomer to Clojure and FP in general, you've created one of the most ergonomic OpenCL wrappers I've ever interacted with (assuming I can get it working!). Even beats out the Intel and AMD template libraries.

**Comment by blueberry** [comment]
please try to simplify the project as much as possible for the beginning. I'd try to run a hello world first, with no aot and uberjar (incanter, etc.) and see whether it works. Also, make sure you run on Java 1.8.
If that does not help, please post that hello world project as a github project, so I can try it on my machine and see whether there is some subtle issue.

**Comment by dkushner** [comment]
I've identified the source of the issue. After forcing Leiningen to do a full recompile, it spat out several errors relating to being unable to find the compiled JOCL library in the class path which is identical to the issue experienced in #4. Sorry about the confusion and rookie mistakes. Hope we get some decent OpenCL support on OS X soon!
